export const defaultValues = {
  firstName: "",
  lastName: "",
  email: "",
  gender: "",
  phone: "",
  dateOfBirth: "",
  subjects: [],
  hobbies: [],
  stateCity: [],
  slider: "",
  language: "",
  address: "",
  file: "",
};
